[tool.poetry]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "*"
stacker_blueprints = "^1.0.8"

[tool.poetry.dev-dependencies]
nose = "^1.3"
mock = "^2.0"
flake8 = "^3.5"
